import { CartProvider } from '../context/CartContext';
import { PointsProvider } from '../context/PointsContext';
import AuthProvider from '../context/AuthProvider';
import '../styles/globals.css';
import Navigation from './components/Navigation';
import MotionPreferences from './components/MotionPreferences';
import type { Metadata } from "next";

const SITE_URL = "https://shop.hackclub.com";
const TITLE = "Hack Club Shop";
const DESCRIPTION =
  "You raised a Hack Clubber. Wear it proudly. Every purchase supports the teenagers who build, ship, and dream at Hack Club.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: TITLE,
    type: "website",
    // og-image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className="antialiased">
        <AuthProvider>
          <PointsProvider>
            <CartProvider>
              <MotionPreferences>
                <Navigation />
                <main id="main-content">{children}</main>
              </MotionPreferences>
            </CartProvider>
          </PointsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
